version: '3.1'

services:
  web:
    env_file: .env
    ports:
      - ${SERVER_PORT}:8000
    depends_on:
      - postgres
    restart: always
    build: 
      context: .
    links:
      - postgres:postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      DATABASE_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  db-data: