version: '3.1'

services:
  web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    ports:
      - ${SERVER_PORT}:8000
    depends_on:
      - postgres
    restart: always
    build: 
      context: .
    links:
      - postgres:postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      DATABASE_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: postgres:latest
    expose:
      - ${DB_PORT}
    volumes:
      - db-data-volume:/var/lib/postgresql:rw
      - ./db/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  db-data-volume:
    external: true